project:
  type: website
  render:
    - "*.md"
    - "*.qmd"

website:

  repo-url: https://github.com/lsc-hubs/quarto-template
  repo-subdir: src
  repo-actions:
    - edit
    - issue
  page-footer:
    left:
    - text: Quarto template
      file: https://github.com/lsc-hubs/quarto-template
  title: "Quarto template"
  search: true
  navbar:
    pinned: true
    logo: https://quarto.org
    right:
      - text: Home
        file: "/"
format: html
